nf-core/rnasplice

conf/test.config
subworkflows/local/align_star.nf
workflows/rnasplice.nf

SL-78 update nf-core module structure imports

---

assets/schema_input.json
bin/check_samplesheet.py

SL-70 Add strandedness,condition and validation code

---

lib/WorkflowRnasplice.groovy
workflows/rnasplice.nf

SL-82 add groovy functions and include valid_params

---

conf/base.config
conf/modules.config
modules/local/edger_exon.nf
modules/local/gffread_tx2gene.nf

SL-84 parametize gff type / add process_single tag

---

workflows/rnasplice.nf

SL-86 refactor ch_samplesheet

---

assets/samplesheet_rmats_error.csv
conf/test.config
lib/WorkflowRnasplice.groovy
nextflow.config
workflows/rnasplice.nf

SL-93 refactor rmarts input checks

---

bin/check_samplesheet.py
bin/dexseq_count.py
bin/dexseq_prepare_annotation.py
bin/filter_gtf_for_genes_in_genome.py

SL-95 format bin python files

---

conf/modules.config
conf/test.config
nextflow.config
subworkflows/local/suppa.nf
workflows/rnasplice.nf

Sl 96 refactor aligner conditional behaviour

---

lib/WorkflowRnasplice.groovy
workflows/rnasplice.nf

Sl 102 add condition check for rmats to groovy script

---

lib/WorkflowRnasplice.groovy

SL-101 add suppa parameter check

---

modules/local/dexseq_dtu.nf
modules/local/dexseq_exon.nf
modules/local/rmats_post.nf
modules/local/rmats_post_single.nf
modules/local/rmats_prep.nf
modules/local/rmats_prep_single.nf
nextflow.config

SL-107 typo correction in dex seq

---

modules/local/rmats_post.nf
modules/local/rmats_post_single.nf
modules/local/rmats_prep.nf
modules/local/rmats_prep_single.nf
nextflow.config

SL-98 add rmats mulled container, resolve dexseq bug

---

conf/modules.config

SL-105 add getchromsizes to modules conf

---

conf/modules.config

SL-108 add single prep to withname pattern

---

lib/WorkflowRnasplice.groovy
workflows/rnasplice.nf

SL-106 check denominator specified correctly

---

lib/WorkflowRnasplice.groovy

SL-112 add warning for user

---

conf/modules.config

SL-104 fix withname pattern

---

modules/local/rmats_post.nf
modules/local/rmats_post_single.nf

SL-98 rmats read length correction

---

conf/modules.config

SL-118 respec modules conf

---

conf/modules.config

SL-119 add gtf_gene_filter to modules.config

---

conf/modules.config
nextflow.config
subworkflows/local/prepare_genome.nf
workflows/rnasplice.nf

SL-117 fix featurecounts spec

---

conf/modules.config

Hi, 
There is currently no rule to publish the outputs of the salmon star quantification process. This PR adds a section in modules.config file to publish the output to a specified directory.

SL-17 Include star_salmon_quant rule in modules.config

---

nextflow.config

Hi,
The pipeline was not working using the conda profile for some conda versions. This PR includes enable.conda in the nextflow.config to allow conda to be used.

SL-21 Include enable.conda in configuration

---

conf/test_full.config

fix samplesheet location

---

conf/modules.config
conf/test_edger.config
modules/local/flattengtf.nf
modules/nf-core/star/align/main.nf
modules/nf-core/star/genomegenerate/main.nf
subworkflows/local/edger_deu.nf

fix duplicate exons and star segfault

---

modules/local/rmats_post.nf
modules/local/rmats_post_single.nf
modules/local/rmats_prep.nf
modules/local/rmats_prep_single.nf

update singularity and docker containers

---

tower.yml

add basic tower.yml file

---

nextflow_schema.json

remove default values specified as None

---

modules/local/rmats_post.nf
modules/local/rmats_post_single.nf
modules/local/rmats_prep.nf
modules/local/rmats_prep_single.nf

update process capacity

---

subworkflows/local/prepare_genome.nf

Fixed the issue (gencode -> params.gencode) in prepare_genome.nf subworkflow. Issue #60

Fixed params.gencode in prepare_genome - issue #60

---

bin/run_edger_exon.R

keep contrasts as array when only one level

---

subworkflows/local/rmats.nf
subworkflows/local/tx2gene_tximport.nf

replace across with combine to mimic SQL join

---

modules/local/create_bamlist.nf
modules/local/create_bamlist_single.nf
modules/local/rmats_post.nf
modules/local/rmats_post_single.nf
modules/local/rmats_prep.nf
modules/local/rmats_prep_single.nf
subworkflows/local/rmats.nf

refactor rmats contrasts

---

bin/create_miso_settings.py
bin/parse_miso_index.py
conf/modules.config
modules/local/miso_index.nf
modules/local/miso_run.nf
modules/local/miso_sashimi.nf
modules/local/miso_settings.nf
subworkflows/local/visualise_miso.nf

Potential fix for MISO index issue #90

Potential fix for MISO index issue

---

README.md
lib/WorkflowMain.groovy
nextflow.config

add zenodo doi

---

assets/contrastsheet.csv

Add missing example contrastsheet

---

CHANGELOG.md
bin/run_dexseq_dtu.R
bin/run_dexseq_exon.R
bin/run_drimseq_filter.R
bin/run_edger_exon.R
bin/suppa_split_file.R

This PR addresses the issue #122

Stop R converting sample names with '-' in string
